SELECT e.ID, ifnull(c.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS e
LEFT JOIN (
    SELECT PARENT_ID AS ID, count(ID) AS CHILD_COUNT
    FROM ECOLI_DATA 
    GROUP BY PARENT_ID
    ) AS c ON e.ID = c.ID
ORDER BY e.ID ASC;