-- 코드를 입력하세요
SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, r.SCORE
FROM REST_INFO AS i
JOIN (
    SELECT REST_ID, round(avg(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) AS r ON i.REST_ID = r.REST_ID
WHERE i.ADDRESS LIKE "서울%"
ORDER BY r.SCORE DESC, i.FAVORITES DESC;
