-- 코드를 작성해주세요
SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_TREE AS t
JOIN ITEM_INFO AS i ON i.ITEM_ID = t.ITEM_ID
JOIN ITEM_INFO AS p ON p.ITEM_ID = t.PARENT_ITEM_ID
WHERE p.RARITY = "RARE"
ORDER BY i.ITEM_ID DESC;